# Generated by Django 6.0.1 on 2026-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_reference_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='situation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
