name: Setup backend toolchain
description: Setup Python, cache pip, and install backend requirements

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  working-directory:
    description: Backend working directory
    required: false
    default: "backend"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.working-directory }}/requirements.txt

    - name: Install backend dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        python -m pip install --no-cache-dir --index-url https://pypi.org/simple -r requirements.txt
