apiVersion: 1

contactPoints:
  - orgId: 1
    name: critical-webhook
    receivers:
      - uid: critical-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: ${GRAFANA_ALERT_WEBHOOK_URL}
          httpMethod: POST
          maxAlerts: 0
